### ISSUE TITLE
Updating stopped it from working

### ISSUE THREAD

**Issue by fourroses666** [mplavala/webpconverter#4]
I have updated the plugin but there is something in plugin.webpconverter.php which stopped it from working on my site.

**Comment by mplavala** [comment]
I need more info: does it throw any errors, or are the images just ignored? In what form are the paths to the images?

To get PHP8 compatibility, I had to change how the MIME types of images are detected. This causes a bug where sometimes the plugin thinks the image is external and should not be converted, e.g. when using path `/assets/images/image.png` instead of `assets/images/image.png`. So maybe this could be the issue. If it is so, then just hold tight, I will fix it.

**Comment by fourroses666** [comment]
I see no system log errors, I do have an error but that's because I uploaded a far too large image with FTP.
`Allowed memory size of 134217728 bytes exhausted (tried to allocate 96000000 bytes)`

Image path looks like this: /ff/1.jpg    PHP 7.4

I will test right now if its the "/"

By the way; On front-end the .jpg images where shown so no blank screen or something ':-)

**Comment by fourroses666** [comment]
Yes its the / which causes the image not to be converted.

**Comment by fourroses666** [comment]
The old version works but the latest one (Extras) doesn't, with or without the / on a site with EVO 3.1.2

**Comment by mplavala** [comment]
Can you send the link to the site, so I can see it? Also, what is the PHP version?

**Comment by fourroses666** [comment]
Can you send me an email so I have yours? PHP 7.4
