### ISSUE TITLE
meta og:image and .webp

### ISSUE THREAD

**Issue by fourroses666** [mplavala/webpconverter#6]
Hey, is there a way to exclude and image from being converted to .webp?

I don't think meta _og:image_ and _twitter:image_ can be .webp

**Comment by mplavala** [comment]
No, but the plugin only searches for images that are in `<img src="...">`, `<video poster="...">`, and `<source srcset="...">`. The plugin ignores images in `<meta>` tags. I don't even plan to add support for converting images in `<meta>` tags, because they are not rendered to a user visiting your site, so changing them to webp does not speed up the site.
Moreover the plugin checks http headers whether the user/robot accepts webp (so that it does not show webp to people on IE6 and Safari), and also the bots should set that header correctly to indicate, whether they want webp or not.

**Comment by fourroses666** [comment]
Ah your right. Didn't overthink and tested it yet because my site still in development and didn't add the plugin yet.
