### ISSUE TITLE
Use in multiTV and PHPthumb

### ISSUE THREAD

**Issue by fourroses666** [mplavala/webpconverter#7]
I use MultiTV:
```
[!multiTV?
&tvName=`partners`
&docid=`[*id*]`
&outerTpl=`@CODE:((wrapper))`
&rowTpl=`partners-tpl`
&display=`40`
!]
```

partners TPL:
```
[!webpBackground? &src=`[!phpthumb? &input=`[+image+]` &options=`w=400,h=280,far=1,bg=ffffff`!]`!]
```

Results into: 
```<img src="%5B!webpBackground?%20&amp;src=%60%5B!phpthumb?%20&amp;input=%60assets/images/partners/logo.png%60%20&amp;options=%60w=400,h=280,far=1,bg=ffffff%60!%5D%60!%5D">```

Its not possible to use the snippet in a snippet like this?

Another try on a banner:
```
[!webpBackground? &src=`[!phpthumb? &input=`[*banner*]` &options=`w=1680`!]`!]
```

Get an error;
REQUEST_URI | http://my-site.nl:443/contact

Did notice http instead of https
-- | --

**Comment by mplavala** [comment]
This is likely not an issue within WebP Converter, but more about interactions of snippets within Evo CMS.

For using a snippet inside MultiTV: it seems that MultiTV converts the special characters inside the chunk partners-tpl into HTML entities, hence the snippets do not get parsed. What works for me here is to use a MultiTV template in assets/tvs/multitv/configs/foobar.confing.inc.php instead of the chunk and there I include the snippet and it is parsed correctly. Actually, if using MultiTV like this, I have to use a snippet inside the config file to convert special characters to HTML entities myself in order to not screw up the text encoding.

For the second case: is this also inside MultiTV, or is this inside a template/chunk?

**Comment by fourroses666** [comment]
Hmm, oke yes you are right its not a WebP Converter issue.

Thanks for the MultiTV solution. Its also the case in a normal chunk. 
I have a simple background `[*banner*]` image and would like to convert that but can't use phpthumb in the webPbackground snippet and guess that won't work in the template too.
```[!webpBackground? &src=`[!phpthumb? &input=`[*banner*]` &options=`w=1680`!]`!]```

It seems phpthumb can convert to webp now too. (EVO 1.3.6) But I think your solution is better because of the fallback.
phpthumb just add &webp='1' to the call. But also need to install [ this](https://packagist.org/packages/rosell-dk/webp-convert) package with Console.

**Comment by mplavala** [comment]
> I have a simple background `[*banner*]` image and would like to convert that but can't use phpthumb in the webPbackground snippet and guess that won't work in the template too.
> `` [!webpBackground? &src=`[!phpthumb? &input=`[*banner*]` &options=`w=1680`!]`!] ``

This should work without MultiTV, or at least it works on my dev server where I test the snippet, so if it fails for you, then this is a problem with WebP Converter. To be more exact, I use phpThumb inside webpBackground inside a chunk and all works as expected. Just maybe turn on caching for phpThumb.

**Comment by fourroses666** [comment]
Hmm, need to look at it, this below does work on the site I'm now working on.
```<div class="wrap" style="background-image:url([!webpBackground? &src=`[[phpthumb? &input=`[*banner*]` &options=`w=1480`]]`!])">```
